[package]
name = "arctic-rocksdb"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[dependencies]
arctic = { path = "../../../arctic", default-features = false, features = ["opt-node3-get", "opt-node15-get"] }
mimalloc = "0.1.48"
